### ISSUE TITLE
Can we get "member since" information for legislators?

### ISSUE THREAD

**Issue by erinspace** [jamesturk/tot#69]

**Comment by jamesturk** [comment]
the only regular source of this data seems to be http://www.myfloridahouse.gov/Sections/Representatives/representatives.aspx which just lists all their start dates as of this term

there is biographical text that'd be a pain to extract in a reliable fashion, so if we really need this it'll probably have to be manually entered

**Comment by erinspace** [comment]
A plan is in place!

**Comment by jamesturk** [comment]
I need to load the spreadsheet into extras, can surface the new data there

**Comment by jamesturk** [comment]
should be available in person.extras.member_since

**Comment by erinspace** [comment]
Should work with the redeploy @jamesturk ! I'll wait to check it out on the server before closing this one out.

**Comment by erinspace** [comment]
Looks good! :hamster:
